### ISSUE TITLE
Error getting cgradapter-android version 0.3.3 from terraframe repository

### ISSUE THREAD

**Issue by Kigamba** [terraframe/common-geo-registry-adapter#22]
I am getting this error when I try to build the geowidget

```
Could not get resource 'http://nexus.terraframe.com/content/groups/allrepos/com/cgr/adapter/cgradapter-android/0.3.3/cgradapter-android-0.3.3.pom
```

Is the artefact still available?

**Comment by justinlewis** [comment]
We migrated from Nexus to Cloud Smith as part of addressing issues with the log4j vulnerability. All the dependencies can be found [here](https://cloudsmith.io/~terraframe/repos/geoprism-registry/packages/) however we don't have them for versions that old. Are you using this dependency?

If so we should look into how you're using it since that version is very out of date. We're currently on 0.18.x releases.

**Comment by ekigamba** [comment]
Thanks @justinlewis . I'll see what I can do about this and get back if I face any siginficant API changes that I have difficulty understanding

**Comment by rrowlands** [comment]
I'm also not sure what server you intend to communicate with using the adapter but the reveal-georegsitry.geoprism.net server is no longer up either.

**Comment by ekigamba** [comment]
@rrowlands Thanks. What about `https://georegistry.geoprism.net`

**Comment by jsmethie** [comment]
Closed due to inactivity
